### ISSUE TITLE
Dependency on vendored repo blocks publishing

### ISSUE THREAD

**Issue by kenz-gelsoft** [kenz-gelsoft/wxRust2#162]
```
kenz@KENZnoMacBook-Air wx-base % cargo publish
    Updating crates.io index
error: all dependencies must have a version specified when publishing.
dependency `wx-universal-apple-darwin` does not specify a version
Note: The published dependency will use the version from crates.io,
the `git` specification will be removed from the dependency declaration.
```

**Comment by kenz-gelsoft** [comment]
I thought optional dependency will be allowed on publishing. But it wasn't.

@ancwrd1 Could you give me any advice on this?

**Comment by ancwrd1** [comment]
You mean publish on crates.io?
I think it requires that the dependency is also there but I haven't published them yet.

**Comment by ancwrd1** [comment]
I can probably publish version 0.1.0 or similar, but I also wanted to upgrade it first to wx 3.2, currently it's on 3.1.6.

**Comment by kenz-gelsoft** [comment]
Yes, I mean publishing on crates.io as an alpha release for now.

It is OK publishing your vendored crates too, but I think those repo are a bit special to be hosted on crates.io.

So I want to find another way to incorporate them into wxRust.

**Comment by kenz-gelsoft** [comment]
I prefer not specifying any real prebuilt binary crate.

c.f.
- Let both wxrust-config and vendor crate have same API and replacing by latter.
- Introduce placeholder crate and repkace with actual vebdor repo.

**Comment by kenz-gelsoft** [comment]
I searched cargo command line option to override dependency temporarily, but not exist.

I'll explore an way to move those dependency out from library crates to sample crates.

**Comment by ancwrd1** [comment]
One solution could be to create a `wx-src` source-only crate which builds wxWidgets on the fly, similar to e.g. https://github.com/alexcrichton/openssl-src-rs and have it under `vendored` feature gate.
It will surely significantly increase build times but only for the first build, and in many cases that might be acceptable.

**Comment by kenz-gelsoft** [comment]
Thank you for taking time on this.

I'm trying following approach:
- Simplify wxrust-config API requiement on #501
- Add runtime (not buildtime) same API implementation for vendored crates (I will open PR for your crates)
- Override dependency only on sample executable crates (won't be published at crates.io)

**Comment by kenz-gelsoft** [comment]
Accidentally closed, reopen.

**Comment by kenz-gelsoft** [comment]
#166 may work for single vendored repo by overriding wxrust-config dependency.

This mechanism doesn't work per-target repo.

I'll try to make a git repo crate (won't be published) to support multiple build-target vendoring.

- Create new repo(crate)
  - `wxrust-vendored-config` which has same metadata with wxrust-config crate.
  - Multiple crates with same metadata in one workspace is not allowed, so this must be another repo.
  - This crate provides same crate surface with wxrust-config crate by using https://github.com/kenz-gelsoft/wx-x86_64-pc-windows-msvc/pull/2 like runtime API for multiple prebuilt crates.
- This repo overrides wxrust-config 0.0.1 with `patch.crates-io` new crate.

**Comment by kenz-gelsoft** [comment]
Next, I'll try the placeholder approch if work.

The current approch doesn't work with cross toolchain situation as https://github.com/kenz-gelsoft/wxRust2/pull/166#issuecomment-1238736318.
