### ISSUE TITLE
Turn wxSOME_IDENTIFIER into wx::SOME_IDENTIFIER

### ISSUE THREAD

**Issue by ahenshaw** [kenz-gelsoft/wxRust2#38]
In the same fashion that wxPython creates a wx namespace, use a more Rust-typical naming convention.

**Comment by kenz-gelsoft** [comment]
Thank you feedback, wanna improve this before 1.0 release after more usable and complete API coverage.

I didn't investigate how wxPython generate these constants yet, do you have an idea how we should treat this?

Just stripping the wx prefix if found and placing them in the wx module are enough?

**Comment by ahenshaw** [comment]
That's pretty much it.  Not everything is in the root namespace, but I believe wx is stripped from everything.  Which makes sense, the old naming convention predates widespread use of namespaces, but now it's just redundant.

**Comment by kenz-gelsoft** [comment]
note for myself:
- consider mapping C enums to https://github.com/bitflags/bitflags especially inner enum of some classes recently introduced
